# Uncomment the next line to define a global platform for your project
#platform :ios, '8.0'
# Comment the next line if you don't want to use dynamic frameworks  
use_frameworks!

target 'Doldamgil' do

  # Pods for Doldamgil
	pod 'FSCalendar'
        pod 'SwiftyJSON', '~> 4.0'
	pod 'Alamofire', '~> 5.2'
	pod 'Charts'
	pod 'AWSS3'

  target 'DoldamgilTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DoldamgilUITests' do
    # Pods for testing
  end

end
